server:
  port: 8084

logging:
  level:
    org.springframework: INFO
    ru.unit_techno.qr_entry_control_impl: DEBUG

ws:
  topics:
    name: "/qr-entry-control/events"

spring:
  application:
    name: qr-entry-control
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: qr_entry_control
        use_sql_comments: true
        format_sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATASOURCE_MAIN_DSN:jdbc:postgresql://localhost:5432/unit_techno?currentSchema=qr_entry_control}
    username: ${DATASOURCE_MAIN_USERNAME:qr_entry_admin}
    password: ${DATASOURCE_MAIN_PASSWORD:squd}
  thymeleaf:
    encoding: UTF-8
  mail:
    host: smtp.yandex.ru
    port: 465
    username: crime-it-tech-user@yandex.ru
    password: jrRJnutB0t
    properties:
      mail:
        debug: true
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true

qr-entry-control:
  cron:
    #real cron "0 0 0 * * *"  real timezone "Europe/Moscow"
    delete-expired-qr-job: "*/30 * * * * *"
    expiring-old-qr-job: "*/45 * * * * *"
    time-zone: "Europe/Moscow"

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

event:
  type:
    1239:
      info: "административный корпус"
      entryType: OUT
    2345:
      info: "задний проход"
      entryType: IN